# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from functools import partial
from pprint import pprint
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap

class Ui_MainWindow(object):
    def __init__(self):
        self.buttons = []
        self.label = QtWidgets.QLabel()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        _translate = QtCore.QCoreApplication.translate

        # Area 0

        self.scrollArea_4 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_12 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_12.setGeometry(QtCore.QRect(0, 0, 196, 409))
        self.scrollAreaWidgetContents_12.setObjectName("scrollAreaWidgetContents_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")

        self.runButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_12)
        self.runButton.setObjectName("runButton")
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.verticalLayout_6.addWidget(self.runButton)

        self.editButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_12)
        self.editButton.setObjectName("editButton")
        self.editButton.setText(_translate("MainWindow", "Edit"))
        self.verticalLayout_6.addWidget(self.editButton)

        self.removeButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_12)
        self.removeButton.setObjectName("removeButton")
        self.removeButton.setText(_translate("MainWindow", "Remove"))
        self.verticalLayout_6.addWidget(self.removeButton)

        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_12)
        self.horizontalLayout_8.addWidget(self.scrollArea_4)

        # Area 1

        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_9 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 196, 409))
        self.scrollAreaWidgetContents_9.setObjectName("scrollAreaWidgetContents_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(partial(self.buttonClicks, "move 10 inches"))
        self.verticalLayout_4.addWidget(self.pushButton)
        self.pushButton_17 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_17.clicked.connect(partial(self.buttonClicks, "pushButton_17"))
        self.verticalLayout_4.addWidget(self.pushButton_17)
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(partial(self.buttonClicks, "pushButton_6"))
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(partial(self.buttonClicks, "pushButton_9"))
        self.verticalLayout_4.addWidget(self.pushButton_9)
        self.pushButton_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.clicked.connect(partial(self.buttonClicks, "pushButton_14"))
        self.verticalLayout_4.addWidget(self.pushButton_14)
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(partial(self.buttonClicks, "pushButton_10"))
        self.verticalLayout_4.addWidget(self.pushButton_10)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_9)
        self.horizontalLayout_8.addWidget(self.scrollArea)

        # Area 2

        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_10 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_10.setGeometry(QtCore.QRect(0, 0, 197, 409))
        self.scrollAreaWidgetContents_10.setObjectName("scrollAreaWidgetContents_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_10)
        self.horizontalLayout_8.addWidget(self.scrollArea_2)

        # Area 3
        

        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_11 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_11.setGeometry(QtCore.QRect(0, 0, 196, 409))
        self.scrollAreaWidgetContents_11.setObjectName("scrollAreaWidgetContents_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_11)
        self.verticalLayout_6.setObjectName("verticalLayout_6")

        # Adding image
        
        self.pixmap = QPixmap('Images/Cats.png')
        self.label.setPixmap(self.pixmap)
        self.label.resize(5, 5)
        self.verticalLayout_6.addWidget(self.label)

        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_11)
        self.horizontalLayout_8.addWidget(self.scrollArea_3)

        # Main Window

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 24))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Move"))
        self.pushButton_17.setText(_translate("MainWindow", "Loop"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_14.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton"))

    def buttonClicks(self, buttonName):
        self.buttons.append(QtWidgets.QPushButton(buttonName,self.scrollAreaWidgetContents_10))
        length = len(self.buttons)
        self.buttons[length - 1].setObjectName("pushButton" + str(length + 20))
        self.verticalLayout_5.addWidget(self.buttons[length - 1])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
