# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from calendar import c
from pickle import TRUE
from unicodedata import name
import backend
from cProfile import label
from copyreg import constructor
from functools import partial
from pprint import pprint
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import *
from PyQt5.QtWidgets import QLabel, QInputDialog
from PyQt5.QtWidgets import *
# from file_with_ui import Ui_MainWindow

class Main(QMainWindow):
    def __init__(self):
        self.buttons = []
        self.variables = []
        self.label = QtWidgets.QLabel()
        self.speed = 15
        self.is_removed = 0
        self.is_run = 0
        self.is_edited = 0
        self.num_buttons =0
        self.dict = {}
        self.obj1=backend.target_object('images.jpg')
        self.var = backend.variable()
        self.list_loop_buttons = []
        self.run_stack = []
        self.button_list = []
        self.if_list = []
        self.else_list = []
        self.bool_if_list = []
        self.execute_if = []
        self.execute_while = []
        self.prev = 0
        self.operators = backend.operators()
        super().__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        _translate = QtCore.QCoreApplication.translate

        # Area 0

        self.scrollArea_4 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_12 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_12.setGeometry(QtCore.QRect(0, 0, 196, 409))
        self.scrollAreaWidgetContents_12.setObjectName("scrollAreaWidgetContents_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")

        self.runButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_12)
        self.runButton.setObjectName("runButton")
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.runButton.clicked.connect(self.new_run)
        #self.runButton.setStyleSheet("background-color : yellow")
        self.runButton.setStyleSheet("QPushButton"
                             "{"
                             "background-color : lightblue;"
                             "}"
                             "QPushButton::pressed"
                             "{"
                             "background-color : green;"
                             "}"
                             )
        self.verticalLayout_6.addWidget(self.runButton)

        # self.editButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_12)
        # self.editButton.setObjectName("editButton")
        # self.editButton.setStyleSheet("QPushButton"
        #                      "{"
        #                      "background-color : lightblue;"
        #                      "}"
        #                      "QPushButton::pressed"
        #                      "{"
        #                      "background-color : green;"
        #                      "}"
        #                      )
        # self.editButton.setText(_translate("MainWindow", "Edit"))

        # self.verticalLayout_6.addWidget(self.editButton)

        self.removeButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_12)
        self.removeButton.setObjectName("removeButton")
        self.removeButton.setText(_translate("MainWindow", "Remove"))
        self.removeButton.setStyleSheet("QPushButton"
                             "{"
                             "background-color : lightblue;"
                             "}")
        # self.removeButton.clicked.connect(self.clickme)
        self.removeButton.clicked.connect(self.remove)
        self.verticalLayout_6.addWidget(self.removeButton)

        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_12)
        self.horizontalLayout_8.addWidget(self.scrollArea_4)

        

        self.ready_to_select = QtWidgets.QPushButton(self.scrollAreaWidgetContents_12)
        self.ready_to_select.setObjectName("ready to select")
        self.ready_to_select.setText(_translate("MainWindow", "Ready to select"))
        self.ready_to_select.setStyleSheet("QPushButton"
                             "{"
                             "background-color : lightblue;"
                             "}")
        self.ready_to_select.clicked.connect(self.ready_to_connect)
        self.verticalLayout_6.addWidget(self.ready_to_select)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_12)
        self.horizontalLayout_8.addWidget(self.scrollArea_4)

        # Area 1

        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_9 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 196, 409))
        self.scrollAreaWidgetContents_9.setObjectName("scrollAreaWidgetContents_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(partial(self.buttonClicks, "Move"))
        self.verticalLayout_4.addWidget(self.pushButton)

        self.pushButton_17 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_17.setObjectName("pushButton_3")
        self.pushButton_17.clicked.connect(partial(self.buttonClicks, "Loop"))
        self.verticalLayout_4.addWidget(self.pushButton_17)

        self.pushButton_if = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_if.setObjectName("pushButton_if")
        self.pushButton_if.clicked.connect(partial(self.buttonClicks, "If"))
        self.verticalLayout_4.addWidget(self.pushButton_if)

        self.pushButton_endif = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_endif.setObjectName("pushButton_endif")
        self.pushButton_endif.clicked.connect(partial(self.buttonClicks, "Endif"))
        self.verticalLayout_4.addWidget(self.pushButton_endif)

        self.pushButton_else = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_else.setObjectName("pushButton_else")
        self.pushButton_else.clicked.connect(partial(self.buttonClicks, "Else"))
        self.verticalLayout_4.addWidget(self.pushButton_else)

        self.pushButton_elseend = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_elseend.setObjectName("pushButton_elseend")
        self.pushButton_elseend.clicked.connect(partial(self.buttonClicks, "Endelse"))
        self.verticalLayout_4.addWidget(self.pushButton_elseend)

        self.pushButton_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_16.clicked.connect(partial(self.buttonClicks, "End Loop"))
        self.verticalLayout_4.addWidget(self.pushButton_16)

        self.pushButton_while = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_while.setObjectName("pushButton_while")
        self.pushButton_while.clicked.connect(partial(self.buttonClicks, "while"))
        self.verticalLayout_4.addWidget(self.pushButton_while)

        self.pushButton_endwhile = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_endwhile.setObjectName("pushButton_endwhile")
        self.pushButton_endwhile.clicked.connect(partial(self.buttonClicks, "endwhile"))
        self.verticalLayout_4.addWidget(self.pushButton_endwhile)

        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(partial(self.buttonClicks, "Rotate"))
        self.verticalLayout_4.addWidget(self.pushButton_6)

        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(partial(self.buttonClicks , "Create Variable"))
        self.verticalLayout_4.addWidget(self.pushButton_9)

        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(partial(self.buttonClicks, "Show Variable"))
        self.verticalLayout_4.addWidget(self.pushButton_10)

        self.pushButton_incr = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_incr.setObjectName("pushButton_incr")
        self.pushButton_incr.clicked.connect(partial(self.buttonClicks, "Incr Variable"))
        self.verticalLayout_4.addWidget(self.pushButton_incr)

        self.pushButton_18 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_18.clicked.connect(partial(self.buttonClicks, "Add"))
        self.verticalLayout_4.addWidget(self.pushButton_18)

        self.pushButton_19 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_19.clicked.connect(partial(self.buttonClicks, "Sub"))
        self.verticalLayout_4.addWidget(self.pushButton_19)        

        self.pushButton_20 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_20.clicked.connect(partial(self.buttonClicks, "Div"))
        self.verticalLayout_4.addWidget(self.pushButton_20)

        self.pushButton_21 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_9)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_21.clicked.connect(partial(self.buttonClicks, "Mul"))
        self.verticalLayout_4.addWidget(self.pushButton_21)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents_9)
        self.horizontalLayout_8.addWidget(self.scrollArea)

        # Area 2

        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_10 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_10.setGeometry(QtCore.QRect(0, 0, 197, 409))
        self.scrollAreaWidgetContents_10.setObjectName("scrollAreaWidgetContents_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_10)
        self.horizontalLayout_8.addWidget(self.scrollArea_2)

        # Area 3
        

        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_11 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_11.setGeometry(QtCore.QRect(0, 0, 196, 409))
        self.scrollAreaWidgetContents_11.setObjectName("scrollAreaWidgetContents_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_11)
        self.verticalLayout_6.setObjectName("verticalLayout_6")

       # self.pixmap = QPixmap('images.jpg')
        #self.pixmap = self.pixmap.scaled(QtCore.QSize(100, 100))
        # self.label.move(1000, 1000)
        #self.label.setPixmap(self.pixmap)
        #self.label.resize(self.pixmap.width(), self.pixmap.height())

        #print(self.label.x())
        #print(self.label.y())
        self.verticalLayout_6.addWidget(self.obj1.label)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_11)
        self.horizontalLayout_8.addWidget(self.scrollArea_3)

        # Main Window

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 24))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Move"))
        self.pushButton_17.setText(_translate("MainWindow", "Loop"))
        self.pushButton_if.setText(_translate("MainWindow", "If"))
        self.pushButton_endif.setText(_translate("MainWindow", "Endif"))
        self.pushButton_else.setText(_translate("MainWindow", "Else"))
        self.pushButton_elseend.setText(_translate("MainWindow", "Endelse"))
        self.pushButton_6.setText(_translate("MainWindow", "Rotate"))
        self.pushButton_9.setText(_translate("MainWindow", "Create Variable"))
        self.pushButton_10.setText(_translate("MainWindow", "Show Variable"))
        self.pushButton_incr.setText(_translate("MainWindow", "Incr Variable"))
        self.pushButton_16.setText(_translate("MainWindow", "End Loop"))
        self.pushButton_while.setText(_translate("MainWindow", "while"))
        self.pushButton_endwhile.setText(_translate("MainWindow", "endwhile"))
        self.pushButton_18.setText(_translate("MainWindow", "Add"))
        self.pushButton_19.setText(_translate("MainWindow", "Sub"))
        self.pushButton_20.setText(_translate("MainWindow", "Div"))
        self.pushButton_21.setText(_translate("MainWindow", "Mul"))

    def buttonClicks(self, buttonName):
        but = QtWidgets.QPushButton(buttonName,self.scrollAreaWidgetContents_10)
        but.setObjectName(str(self.num_buttons))
        but.setStyleSheet("QPushButton""{""background-color : lightblue;""}")
        self.dict[self.num_buttons] = but
        self.num_buttons+=1
        self.buttons.append(but)
        length = len(self.buttons)
        but.clicked.connect(partial(self.popUp, buttonName, but))
        self.verticalLayout_5.addWidget(but)

    def move_image(self):
        # self.label.move(self.label.x() + 10, self.label.y() + 10)
        self.label.move(self.label.x() + 1, self.label.y())
        # print(self.label.x())
        # print(self.label.y())

    def to_run_blocks():
        return

    def ready_to_connect(self):
        if self.ready_to_select.styleSheet() == "QPushButton{background-color : lightblue;}":
            self.ready_to_select.setStyleSheet("QPushButton""{""background-color : green;}")

        elif self.ready_to_select.styleSheet() == "QPushButton{background-color : green;}":
            self.ready_to_select.setStyleSheet("QPushButton""{""background-color : lightblue;}")
            for key in self.dict:
                self.dict[key].setStyleSheet("QPushButton""{""background-color : lightblue;}")

    def donothing(self):
        return                   

    def clickme(self):
        if self.is_removed == 0:
            self.removeButton.setStyleSheet("QPushButton{background-color : green;}")
            self.is_removed = 1
            print(self.removeButton.styleSheet())
        else:
            self.removeButton.setStyleSheet("QPushButton{background-color : lightblue;}")
            self.is_removed = 0

                
        # print("pressed")                     

        # printing pressed       

    def keyPressEvent(self, event):
  
        # get the current co-ordinates of the label
        # X Co-ordinate
        x = self.label.x()
  
        # Y Co-ordinate
        y = self.label.y()
  
        # if up arrow key is pressed
        if event.key() == Qt.Key_Up:
            self.label.move(x, y - self.speed)
  
        # if down arrow key is pressed
        elif event.key() == Qt.Key_Down:
            self.label.move(x, y + self.speed)
  
        # if left arrow key is pressed
        elif event.key() == Qt.Key_Left:
            self.label.move(x - self.speed, y)
  
        # if down arrow key is pressed
        elif event.key() == Qt.Key_Right:
            self.label.move(x + self.speed, y)

    def add_loop_in_stack(self):
        self.list_loop_buttons = self.list_loop_buttons[::-1]
        
        #for i in self.list_loop_buttons:
           #print("Blocks in loop: " + i.text())


        buttonname=self.list_loop_buttons[0].text()

        x = buttonname.split()
        val = int(x[1])
        # print('val of loop:'+ str(val))
        if(x[0]=="Loop"):
            _translate = QtCore.QCoreApplication.translate
            self.list_loop_buttons[0].setText(_translate("MainWindow", "start_loop"))
            self.list_loop_buttons[len(self.list_loop_buttons)-1].setText(_translate("MainWindow", "end_loop"))
        #self.run_stack.append(self.list_loop_buttons[len(self.list_loop_buttons)-1]) 
        #self.run_stack.append(self.list_loop_buttons[0])
            for j in range(val):  
                for i in range(0,len(self.list_loop_buttons)):
                    self.run_stack.append(self.list_loop_buttons[i])
                    self.prev += 1

        self.list_loop_buttons = []

    def add_button_list_in_run_stack(self):
        # print("Length of run stack: " + str(len(self.list_loop_buttons)))
        self.clear_all_val()
        for i in  range(len(self.button_list)):
            buttonname = self.button_list[i].text()
            x = buttonname.split()
            # print("in_add_button "+str(x))
            if x[0] !="End":
                self.run_stack.append(self.button_list[i])
                self.prev += 1
            else:
                self.run_stack.append(self.button_list[i])
                while(len(self.run_stack)!=0):
                    button = self.run_stack.pop()
                    self.prev -= 1
                    buttonname = button.text()
                    p = buttonname.split()
                    # print("in while loop")
                    if(p[0]=="Loop"):
                        self.list_loop_buttons.append(button)
                        self.add_loop_in_stack()
                        break
                    else:
                        self.list_loop_buttons.append(button)
                        continue

    def clear_all_val(self):
         for k in  range(len(self.button_list)):
            buttonname = self.button_list[k].text()
            x = buttonname.split()
            _translate = QtCore.QCoreApplication.translate
            if(x[0]=="start_loop"):
                self.button_list[k].setText(_translate("MainWindow","Loop"))
            if(x[0]=="end_loop"):
                self.button_list[k].setText(_translate("MainWindow","End"))

    def clear_all_ifs(self):
        for k in range(len(self.button_list)):
            buttonname = self.button_list[k].text()
            x = buttonname.split()
            _translate = QtCore.QCoreApplication.translate
            if(x[0]=="If"):
                self.button_list[k].setText(_translate("MainWindow","If")) 
            if(x[0]=="Else"):
                self.button_list[k].setText(_translate("MainWindow","Else"))           








    def exec_run_stack(self):
        # for j in self.run_stack:
        #     print("Run stack: " + j.text())
        i = 0 
        self.active = False
        self.variable_stack = []
        self.pops = 0
        self.num_pops = []
        self.execute_if = []
        # print("\nprev:" + str(self.prev))
        val3 = len(self.run_stack)
        # print(val3)
        # return 
        while i < val3:          
            buttonName = self.run_stack[i].text()
            x = buttonName.split()
            # print(val)

            if (x[0] == "Move"):
                
                if len(x) == 1:
                    x.append("0")
                    x.append("0")
                
                val_x = self.var.getVariable(x[1])
                val_y = self.var.getVariable(x[2])

                if val_x == None:
                    val_x = int(x[1])
                if val_y == None:
                    val_y = int(x[2])
                   

                if val_x >= 0 and val_y >= 0:
                    # print(x[1])
                    self.obj1.move_right(val_x)
                    self.obj1.move_down(val_y)
                elif val_x >= 0 and val_y <= 0:
                    self.obj1.move_right(val_x)
                    self.obj1.move_up(-val_y)
                elif val_x < 0 and val_y >= 0:
                    # print(int(x[1]))
                    self.obj1.move_left(val_x)
                    self.obj1.move_down(val_y)
                elif val_x < 0 and val_y <= 0:
                    self.obj1.move_left(val_x)
                    self.obj1.move_up(-val_y)

            elif (x[0] == "Rotate"):
                if len(x) == 1:
                    x.append("0")
                # print(x[1])
                self.obj1.rotate(float(x[1]))

            # elif(x[0] == "Edit"):
            #     try:
            #         if(x[2] in self.variables):
            #             array = x[2].split()
            #             condition = ""

            #             for var in array:
            #                 temp = self.var.getVariable(var)

            #                 if (temp != None):
            #                     if (type(temp) is int):
            #                         condition += str(temp)
            #                     elif (type(temp) is str):
            #                         condition += '"' + temp + '"'
            #                     elif (type(temp) is float):
            #                         condition += str(temp)
            #                 else:
            #                     condition += var
            #                 condition += " " 

            #             self.var.setVariable(x[1], eval(condition))
            #     except:
            #         print("Wrong input!\n")
                
            elif(x[0] == "Add"):
                if (len(x) < 3):
                    continue
                
                elif (len(x) == 3):
                    val1 = None
                    val2 = None
                    
                    for j in self.variable_stack:
                        if (j[0] == x[1]):
                            val1 = j[1]

                    for j in self.variable_stack:
                        if (j[0] == x[2]):
                            val1 = j[1]

                    if (val1 == None):
                        val1 = x[1]

                    if (val2 == None):
                        val2 = x[2]

                    print("Addition: ",self.operators.add(val1, val2))
            
            elif(x[0]=="Incr"):
                # print("This is the length of the string:" + str(len(x)))
                if (len(x) < 3): 
                    continue

                elif (len(x) == 3):
                    # print("I am in increment!")
                    val1 = None
                    val2 = x[2]
                    count = 0
                    pos = 0
                    
                    for j in self.variable_stack:
                        if (j[0] == x[1]):
                            val1 = j[1]
                            pos = count
                        count += 1

                    if (val1 == None):
                        continue

                    k = self.operators.add(val1,val2)
                    self.variable_stack[pos][1] = k
                    # print("Increment value:" + str(pos))
                    #print("Addition: ",self.operators.add(val1, val2))

            elif(x[0] == "Sub"):
                if (len(x) < 3):
                    continue
                
                elif (len(x) == 3):
                    val1 = None
                    val2 = None
                    
                    for j in self.variable_stack:
                        if (j[0] == x[1]):
                            val1 = j[1]

                    for j in self.variable_stack:
                        if (j[0] == x[2]):
                            val1 = j[1]

                    if (val1 == None):
                        val1 = x[1]

                    if (val2 == None):
                        val2 = x[2]

                    print("Subtraction: ",self.operators.sub(val1, val2))

            elif(x[0] == "Div"):
                if (len(x) < 3):
                    continue
                
                elif (len(x) == 3):
                    val1 = None
                    val2 = None
                    
                    for j in self.variable_stack:
                        if (j[0] == x[1]):
                            val1 = j[1]

                    for j in self.variable_stack:
                        if (j[0] == x[2]):
                            val1 = j[1]

                    if (val1 == None):
                        val1 = x[1]

                    if (val2 == None):
                        val2 = x[2]

                    print("Division: ",self.operators.div(val1, val2))

            elif(x[0] == "Mul"):
                if (len(x) < 3):
                    continue
                
                elif (len(x) == 3):
                    val1 = None
                    val2 = None
                    
                    for j in self.variable_stack:
                        if (j[0] == x[1]):
                            val1 = j[1]

                    for j in self.variable_stack:
                        if (j[0] == x[2]):
                            val1 = j[1]

                    if (val1 == None):
                        val1 = x[1]

                    if (val2 == None):
                        val2 = x[2]

                    print("Multiplication: ",self.operators.mul(val1, val2))

            elif(x[0]=="If"):
                # print(x)
                temp = str(self.check_condition(buttonName[3:]))
                # print("Condition:" + temp)


                if temp =="False":
                    if (self.active):
                        self.num_pops.append(self.pops)
                        self.pops = 0

                    counter = 0

                    for l in range(i + 1, len(self.run_stack)):
                        temp = self.run_stack[l].text()
                        z = temp.split()

                        if (z[0] == "If"):
                            counter += 1
                        elif (z[0] == "Endif" and counter > 0):
                            counter -= 1
                        elif (z[0] == "Endif" and counter == 0):
                            i = l - 1
                            self.execute_if.append(False)
                            # print("hello!")
                            break

                elif temp=="True":
                    # print("I am in true!")
                    if (self.active):
                        self.num_pops.append(self.pops)
                        self.pops = 0

                    else:
                        self.active = True
                    self.execute_if.append(True)

            elif(x[0]=="Else"):
                # print(x)
                temp = str(self.execute_if.pop())

                if temp =="False":
                    if (self.active):
                        self.num_pops.append(self.pops)
                        self.pops = 0

                    else:
                        self.active = True
                    

                elif temp =="True":
                    if (self.active):
                        self.num_pops.append(self.pops)
                        self.pops = 0

                    else:
                        self.active = True

                    counter = 0
                    # print("hello there!")

                    for l in range(i + 1, len(self.run_stack)):
                        # print("Hello i am here!")
                        temp = self.run_stack[l].text()
                        z = temp.split()

                        if (z[0] == "Else"):
                            counter += 1
                        elif (z[0] == "Endelse" and counter > 0):
                            counter -= 1
                        elif (z[0] == "Endelse" and counter == 0):
                            # print("Hello i am here!")
                            i = l - 1
                            break
                    # print("The value it is jumping to:" + str(i))

            elif(x[0] == "start_loop" or x[0] == "Loop"):
                if (self.active):
                    self.num_pops.append(self.pops)
                    self.pops = 0

                else:
                    self.active = True

            elif(x[0] == "end_loop"):
                while(self.pops != 0):
                    name = self.variable_stack.pop()

                    for k in self.variable_stack:
                        if (name[0] == k[0]):
                            self.var.setVariable(name[0], int(k[1]))

                    self.pops -= 1
                
                if (len(self.num_pops) != 0):
                    self.pops = self.num_pops.pop()

                elif (len(self.num_pops) == 0):
                    self.active = False     


            elif(x[0] == "Variable"):
                if (self.active):
                    self.pops += 1
                    self.var.setVariable(x[1], int(x[2]))

                self.variable_stack.append([x[1], x[2]])

            elif(x[0] == "Endif"):
                while(self.pops != 0):
                    name = self.variable_stack.pop()

                    for k in self.variable_stack:
                        if (name[0] == k[0]):
                            self.var.setVariable(name[0], int(k[1]))

                    self.pops -= 1


                # print("After Endif:" + str(len(self.variable_stack)))
                if (len(self.num_pops) != 0):
                    self.pops = self.num_pops.pop()

                elif (len(self.num_pops) == 0):
                    self.active = False
            
            elif(x[0] == "Show"):
                print(self.variable_stack)
            
            elif(x[0] == "while"):
                temp = str(self.check_condition(buttonName[6:]))

                if temp =="False":
                    counter = 0

                    for l in range(i + 1, len(self.run_stack)):
                        temp = self.run_stack[l].text()
                        z = temp.split()

                        if (z[0] == "while"):
                            counter += 1
                        elif (z[0] == "endwhile" and counter > 0):
                            counter -= 1
                        elif (z[0] == "endwhile" and counter == 0):
                            i = l - 1
                            self.execute_while.append(temp)
                            break

                elif temp=="True":
                    if (self.active):
                        self.num_pops.append(self.pops)
                        self.pops = 0

                    else:
                        self.active = True
                    self.execute_while.append(temp)
            
            elif(x[0] == "endwhile"):
                temp = str(self.execute_while.pop())

                if temp == "False":
                    print("Exiting while!")
                
                elif temp == "True":
                    while(self.pops != 0):
                        name = self.variable_stack.pop()

                        for k in self.variable_stack:
                            if (name[0] == k[0]):
                                self.var.setVariable(name[0], int(k[1]))

                        self.pops -= 1
                    
                    if (len(self.num_pops) != 0):
                        self.pops = self.num_pops.pop()

                    if (len(self.num_pops) == 0):
                        self.active = False

                    counter = 0
                    
                    for l in range(i - 1, -1, -1):
                        temp = self.run_stack[l].text()
                        z = temp.split()

                        if (z[0] == "endwhile"):
                            counter += 1
                        elif (z[0] == "while" and counter > 0):
                            counter -= 1
                        elif (z[0] == "while" and counter == 0):
                            i = l - 1
                            break

                    
            
            elif(x[0] == "Endelse"):
                while(self.pops != 0):
                    name = self.variable_stack.pop()

                    for k in self.variable_stack:
                        if (name[0] == k[0]):
                            self.var.setVariable(name[0], int(k[1]))

                    self.pops -= 1


                # print("After Endif:" + str(len(self.variable_stack)))
                if (len(self.num_pops) != 0):
                    self.pops = self.num_pops.pop()

                elif (len(self.num_pops) == 0):
                    self.active = False
            i += 1

        self.prev = len(self.run_stack)            

    def check_condition(self,i):
        try:
            array = i.split()
            condition = ""

            for var in array:
                temp = None

                for varStack in self.variable_stack:
                    if var == varStack[0]:
                        temp = int(varStack[1])

                if (temp != None):
                    if (type(temp) is int):
                        condition += str(temp)
                    elif (type(temp) is str):
                        condition += '"' + temp + '"'
                    elif (type(temp) is float):
                        condition += str(temp)
                else:
                    condition += var
                condition += " "
            # print("The condition is:" + condition)
             

            if eval(condition):
                return True
            else:
                return False
        except:
            print("An exception occurred")


    def assign_if_else_in_run_stack(self):
        # for j in self.button_list:
        #     print("Inside the assign function:" + j.text())

        for i in range(len(self.run_stack)):
            buttonName = self.run_stack[i].text()
            # print(buttonName)
            x = buttonName.split()
            # print("Lenght of if else:" + str(len(x)))
            # print("in ifelse:" + x[0])
            if x[0]=="If":
                self.if_list.append(i)
                # print("Value:" + str(x[1]))
                self.bool_if_list.append(x[1])
            elif x[0]=="Endif":
                # bt = self.run_stack[self.if_list.pop()]
                _translate = QtCore.QCoreApplication.translate
                it = self.if_list.pop()
                bt = self.run_stack[it].text()
                self.run_stack[it].setText(_translate("MainWindow", bt + " "+str(i)))

            elif x[0]=="Else":
                self.else_list.append(i)
                _translate = QtCore.QCoreApplication.translate
                self.run_stack[i].setText(_translate("MainWindow", buttonName + " "+str(self.bool_if_list.pop())))

            elif x[0]=="Endelse":
                _translate = QtCore.QCoreApplication.translate
                it = self.else_list.pop()
                bt = self.run_stack[it].text()
                self.run_stack[it].setText(_translate("MainWindow", bt + " "+str(i)))
                #self.run_stack[self.else_list.pop()]+= ' ' + str(i)   

    def new_run(self):
        while(len(self.list_loop_buttons) > 0):
            self.list_loop_buttons.pop()
            
        while(len(self.button_list) > 0):
            self.button_list.pop()

        if (self.ready_to_select.styleSheet() == "QPushButton{background-color : lightblue;}"):
            for i in self.buttons:
                # print("Inside button list: " + i.text())
                self.button_list.append(i)
        else:
            for i in self.buttons:
                if i.styleSheet() == "QPushButton{background-color : green;}":
                    self.button_list.append(i)

        while(len(self.run_stack) > 0):
            # print("In the deletion!\n")
            self.run_stack.pop()
        # print("Run stack length before:" + str(len(self.run_stack)))

        # print("Length of list loop buttons:" + str(len(self.list_loop_buttons)))
        # print("Number of buttons: " + str(len(self.buttons)))
        # for i in self.button_list:
        #     print(i.text())
        self.add_button_list_in_run_stack()
        # for i in self.run_stack:
        #     print("In run stack:" + i.text())
        # print("Runs stack length after add button:" + str(len(self.run_stack)))
        # self.assign_if_else_in_run_stack()
        # print("Run stack length after all operations:" + str(len(self.run_stack)))

        self.exec_run_stack()
        self.clear_all_ifs()


    def popUp(self, buttonName, but):
        # print("Button Clicked:" + buttonName)

        if(self.ready_to_select.styleSheet() == "QPushButton{background-color : green;}" and but.styleSheet() == "QPushButton""{""background-color : green;}"):
            but.setStyleSheet("QPushButton""{""background-color : lightblue;}")

        elif (self.ready_to_select.styleSheet() == "QPushButton{background-color : green;}"):
            but.setStyleSheet("QPushButton""{""background-color : green;}")

        elif (buttonName == "Move"):
            _translate = QtCore.QCoreApplication.translate
            x_val, okPressed = QInputDialog.getText(self, "Get integer","Enter x value:")
            y_val, okPressed = QInputDialog.getText(self, "Get integer","Enter y value:")

            if x_val == "" or x_val == None:
                x_val = "0"
            if y_val == "" or y_val == None:
                y_val = "0"

            if okPressed:
                but.setText(_translate("MainWindow", "Move " + x_val + " " + y_val))


        elif (buttonName == "Loop"):
            _translate = QtCore.QCoreApplication.translate
            i, okPressed = QInputDialog.getInt(self, "Get integer","Enter Loop Value:")
        
            if okPressed:
                but.setText(_translate("MainWindow", "Loop " + str(i)))

        elif (buttonName == "Rotate"):
            _translate = QtCore.QCoreApplication.translate
            i, okPressed = QInputDialog.getInt(self, "Get integer","Enter Degree of rotation:")
        
            if okPressed:
                but.setText(_translate("MainWindow", "Rotate " + str(i)))

        elif (buttonName == "Create Variable"):
            _translate = QtCore.QCoreApplication.translate
            name, okPressed = QInputDialog.getText(self, "Get Text","Enter Variable Name:")
            typ, okPressed = QInputDialog.getText(self, "Get Text","Enter Variable Type:")

            if typ == "integer":
                val, okPressed = QInputDialog.getInt(self, "Get Text","Enter Value:")
                but.setText(_translate("MainWindow", "Variable " + name + " " + str(val)))
                self.var.addVariable(name, val)
            else:
                val, okPressed = QInputDialog.getText(self, "Get Text","Enter Value:")
                but.setText(_translate("MainWindow", "Variable " + name + " " + val))
                self.var.addVariable(name, val)

            self.var.addVariable(name, val)

        # elif (buttonName == "Edit Variable"):
        #     _translate = QtCore.QCoreApplication.translate
        #     j, okPressed1 = QInputDialog.getText(self, "Get Text","Enter Variable Name:")

        #     i, okPressed = QInputDialog.getInt(self, "Get Integer","Enter Variable Value:")
        
        #     if okPressed and okPressed1:
        #         but.setText(_translate("MainWindow", "Edit Variable " + str(j) + " " +str(i)))

        elif (buttonName=="End Loop"):
             but.setText(_translate("MainWindow", "End Loop"))


        elif(buttonName=="Incr Variable"):
            _translate = QtCore.QCoreApplication.translate
            i, okPressed = QInputDialog.getText(self, "Get Variable","Enter Variable:")
        
            if okPressed:
                but.setText(_translate("MainWindow", "Incr " + i))

            i, okPressed = QInputDialog.getText(self, "Increment","Enter Increment Value:")
        
            if okPressed:
                but.setText(_translate("MainWindow", but.text()+" "+str(i)))    

        
        elif (buttonName == "Add"):
            _translate = QtCore.QCoreApplication.translate
            i, okPressed = QInputDialog.getText(self, "Get integer","Enter Value:")
        
            if okPressed:
                but.setText(_translate("MainWindow", "Add " + i))
            
            i, okPressed = QInputDialog.getText(self, "Get integer","Enter Value:")

            if okPressed:
                but.setText(_translate("MainWindow", but.text() + " " + i))

        elif (buttonName == "Div"):
            _translate = QtCore.QCoreApplication.translate
            i, okPressed = QInputDialog.getText(self, "Get integer","Enter Value:")
        
            if okPressed:
                but.setText(_translate("MainWindow", "Div " + i))
            
            i, okPressed = QInputDialog.getText(self, "Get integer","Enter Value:")

            if okPressed:
                but.setText(_translate("MainWindow", but.text() + " " + i))

        elif (buttonName == "Sub"):
            _translate = QtCore.QCoreApplication.translate
            i, okPressed = QInputDialog.getText(self, "Get integer","Enter Value:")
        
            if okPressed:
                but.setText(_translate("MainWindow", "Sub " + i))
            
            i, okPressed = QInputDialog.getText(self, "Get integer","Enter Value:")

            if okPressed:
                but.setText(_translate("MainWindow", but.text() + " " + i))

        elif (buttonName == "Mul"):
            _translate = QtCore.QCoreApplication.translate
            i, okPressed = QInputDialog.getText(self, "Get integer","Enter Value:")
        
            if okPressed:
                but.setText(_translate("MainWindow", "Mul " + i))
            
            i, okPressed = QInputDialog.getText(self, "Get integer","Enter Value:")

            if okPressed:
                but.setText(_translate("MainWindow", but.text() + " " + i))
       
        elif(buttonName=="If"):
            _translate = QtCore.QCoreApplication.translate
            i, okPressed = QInputDialog.getText(self, "Get Text","Enter the condition:")
            if okPressed:                
                but.setText(_translate("MainWindow", "If " + i))
        
        elif(buttonName=="while"):
            _translate = QtCore.QCoreApplication.translate
            i, okPressed = QInputDialog.getText(self, "Get Text","Enter the condition:")
            if okPressed:                
                but.setText(_translate("MainWindow", "while " + i))

        elif(buttonName=="endwhile"):
            _translate = QtCore.QCoreApplication.translate
            but.setText(_translate("MainWindow", "endwhile"))
        
        elif(buttonName=="Endif"):
            _translate = QtCore.QCoreApplication.translate
            but.setText(_translate("MainWindow", "Endif"))

        elif(buttonName=="Else"):

            _translate = QtCore.QCoreApplication.translate
            but.setText(_translate("MainWindow", "Else"))

        elif(buttonName=="Endelse"):
            _translate = QtCore.QCoreApplication.translate
            but.setText(_translate("MainWindow", "Elseend"))

    def run(self):
        if (self.ready_to_select.styleSheet() == "QPushButton{background-color : lightblue;}"):
            for i in self.buttons:
                buttonName = i.text()
                x = buttonName.split()
                if (x[0] == "Move"):
                    #self.move_image()

                    if len(x) == 1:
                        x.append("0")
                        x.append("0")

                    if int(x[1]) >= 0 and int(x[2]) >= 0:
                        # print(x[1])
                        self.obj1.move_right(int(x[1]))
                        self.obj1.move_down(int(x[2]))
                    elif int(x[1]) >= 0 and int(x[2]) <= 0:
                        self.obj1.move_right(int(x[1]))
                        self.obj1.move_up(int(-int(x[2])))
                    elif int(x[1]) < 0 and int(x[2]) >= 0:
                        # print(int(x[1]))
                        self.obj1.move_left(int(x[1]))
                        self.obj1.move_down(int(x[2]))
                    elif int(x[1]) < 0 and int(x[2]) <= 0:
                        self.obj1.move_left(int(x[1]))
                        self.obj1.move_up(int(-int(x[2])))

                elif (x[0] == "Rotate"):
                    if len(x) == 1:
                        x.append("0")
                    # print(x[1])
                    self.obj1.rotate(float(x[1]))

                elif(x[0] == "Create"):
                    if len(x) == 2:
                        x.append("0")
                    #print(x[2])
                    self.var.setName(x[2])
                    a = self.var.getVal()
                    self.variables.append(self.var)
                    # print(a)

                # elif(x[0] == "Edit"):
                #     if len(x) == 2:
                #         x.append("0")
                #     if(x[2] in self.variables):
                #         self.var.setVal(x[3])




        else:
            for i in self.buttons:
                if i.styleSheet() == "QPushButton{background-color : green;}":
                    buttonName = i.text()
                    x = buttonName.split()
                    if (x[0] == "Move"):

                        if len(x) == 1:
                            x.append("0")
                            x.append("0")

                        if int(x[1]) >= 0 and int(x[2]) >= 0:
                            # print(x[1])
                            self.obj1.move_right(int(x[1]))
                            self.obj1.move_down(int(x[2]))
                        elif int(x[1]) >= 0 and int(x[2]) <= 0:
                            self.obj1.move_right(int(x[1]))
                            self.obj1.move_up(int(-int(x[2])))
                        elif int(x[1]) < 0 and int(x[2]) >= 0:
                            # print(int(x[1]))
                            self.obj1.move_left(int(x[1]))
                            self.obj1.move_down(int(x[2]))
                        elif int(x[1]) < 0 and int(x[2]) <= 0:
                            self.obj1.move_left(int(x[1]))
                            self.obj1.move_up(int(-int(x[2])))
                    elif (x[0] == "Rotate"):
                        if len(x) == 1:
                            x.append("0")
                        # print(x[1])
                        self.obj1.rotate(float(x[1]))
                    

    def remove(self):
        array = []
        
        for i in self.buttons:
            if (self.ready_to_select.styleSheet() == "QPushButton{background-color : green;}" and i.styleSheet() == "QPushButton""{""background-color : green;}"):
                name = i.text()
                x = name.split()

                if x[0] == "Variable":
                    if len(x) == 3:
                        self.var.remVariable(x[1])
                i.setParent(None)
                array.append(i)


        for i in array:
            self.buttons.remove(i)

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    window = Main()
    window.show()
    sys.exit(app.exec_())


#Comments

    # def select_blocks_to_run(self,button_name):
    #     if self.dict[button_name].styleSheet() == "QPushButton{background-color : lightblue;}":
    #         self.dict[button_name].setStyleSheet("QPushButton{background-color : green;}")
    #     elif self.dict[button_name].styleSheet() == "QPushButton{background-color : green;}":
    #         self.dict[button_name].setStyleSheet("QPushButton{background-color : lightblue;}")
